### ISSUE TITLE
Cannot export mesh with BackSide material

### ISSUE THREAD

**Issue by JackGit** [spite/THREE.CubemapToEquirectangular#9]
I added a dome sphere into the scene, but this sphere can't be exported in pano.
But if I make size smaller without BackSide be set, it is able to exported.

So is there something special to export mesh with BackSide material?

```js
const material = new THREE.MeshBasicMaterial({
				map: textureLoader.load('images/skybox.jpg'),
				emissive: 0x000000,
				transparent: true
			})
			material.side = THREE.BackSide

			scene.add(new THREE.Mesh(
				new THREE.SphereGeometry(3000, 32, 32),
				material
			))
```

**Comment by spite** [comment]
The default CubeCamera has a far range of 1000, so your sphere is probably being clipped. 3000 is a lot of distance for VR, but whatever: read the Unmanaged CubemapToEquirectangular section and create a CubeCamera with the right range for your scene, and it should work.

**Comment by JackGit** [comment]
Thanks for your tip, it helped
